package rules

import bots.bongcloudbot.PlayerDesc.Tight;
import bots.bongcloudbot.PlayerDesc.Aggro;
import bots.bongcloudbot.PlayerDesc;
import bots.bongcloudbot.HandInfo;
import bots.bongcloudbot.BongcloudAction;
import bots.bongcloudbot.StartingHandMatrix;
import bots.bongcloudbot.PlayerActionEvent;
import com.biotools.meerkat.Action;
import com.biotools.meerkat.GameInfo;

global GameInfo gameInfo;

rule "Increase tightness event"
	when
		$event1: PlayerActionEvent($playerName: name, action == Action.FOLD)
		$num: Number(intValue >= 4) from accumulate(
			$event2: PlayerActionEvent(
				this != $event1,
				name == $playerName,
				action == Action.FOLD
			) over window:length(5)
		)
		not (PlayerActionEvent(name == $playerName, action == Action.CALL))
	then
		System.out.println("Rule: " + drools.getRule().getName());
		insert(new ChangeTightnessEvent($playerName, 1);
end

rule "Decrease tightness event"
	when
		$event1: PlayerActionEvent($playerName: name, action == Action.CALL)
		$num: Number(intValue >= 4) from accumulate(
			$event2: PlayerActionEvent(
				this != $event1,
				name == $playerName,
				action == Action.CALL
			) over window:length(5)
		)
		not (PlayerActionEvent(name == $playerName, action == Action.CALL))
	then
		System.out.println("Rule: " + drools.getRule().getName());
		insert(new ChangeTightnessEvent($playerName, -1);
end